<a href="https://colab.research.google.com/github/TALHAREYAZ/Python_Lab/blob/main/Numpy%20Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY OPERATION's**

Creation of array

In [ ]:
import numpy as np
#creating array without range
#1-d array
array=np.arange(20)
print("1-d:\n",array)
#2-d array
array=np.arange(20).reshape(4,5)
print("2-d:\n",array)
#creating array with range
print("array with range:\n",np.arange(0, 15, 2))

1-d:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
2-d:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
array with range:
 [ 0  2  4  6  8 10 12 14]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[2,3,4],[3,4,5]])
#shape
b=a.shape
print("shape:",a.shape)
#dimension
c=a.ndim
print("dimensions:",a.ndim)


shape: (3, 3)
dimensions: 2


Create a matrix full of zeros and ones

In [ ]:
#matrix full of zeros
z=np.zeros((2,2))
print("zeros:\n",z)
#matrix full of ones
o=np.ones((2,2))
print("ones:\n",o)
#creating empty array
a=np.empty((2,3))
print("empty:\n",a)
#creating full array
b=np.full((3,3), 3)
print("Full:\n",b)


zeros:
 [[0. 0.]
 [0. 0.]]
ones:
 [[1. 1.]
 [1. 1.]]
empty:
 [[2.4271611e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]
Full:
 [[3 3 3]
 [3 3 3]
 [3 3 3]]


Reshape and flatten data in the array

In [ ]:
#matrix reshape
a=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
b=a.reshape(4,2,2)
print("reshape:\n",b)
#matrix flatten
c=a.flatten()
print("flatten:\n",c)

reshape:
 [[[1 2]
  [3 4]]

 [[2 3]
  [4 5]]

 [[3 4]
  [5 6]]

 [[4 5]
  [6 7]]]
flatten:
 [1 2 3 4 2 3 4 5 3 4 5 6 4 5 6 7]


 Append data vertically and horizontally

In [ ]:
#Appending data vertically
x=np.array([[10,20],[80,90]])
y=np.array([[30,40],[60,70]])
v=np.vstack((x,y))
print("vertically:\n",v)
#Appending data horizontally
h=np.hstack((x,y))
print("horizontally:\n",h)

vertically:
 [[10 20]
 [80 90]
 [30 40]
 [60 70]]
horizontally:
 [[10 20 30 40]
 [80 90 60 70]]


Apply indexing and slicing on array

In [ ]:
#indexing
a=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
temp = a[[0, 1, 2, 3], [1, 1, 1, 1]]
#slicing
i=a[:4,::2]
print("slicing:\n",i)

slicing:
 [[1 3]
 [2 4]
 [3 5]
 [4 6]]


Use statistical functions on array - **Min, Max, Mean, Median and Standard Deviation**


In [ ]:
#min for finding minimum of an array
a=np.array([[1,3,-1,4],[3,-2,1,4]])
b=a.min()
print('min:\n ',b)
#max for finding maximum of an array
c=a.max()
print('max:\n',c)
#mean
a=np.array([1,2,3,4,5])
d=a.mean()
print("mean:\n",d)
#median
e=np.median(a)
print("median:\n",e)
#standard deviation
f=a.std()
print("SD:\n",f)

min:
  -2
max:
 4
mean:
 3.0
median:
 3.0
SD:
 1.4142135623730951


Arithmetic Operations in Numpy 

In [ ]:
arr1 = np.arange(4, dtype = np.float_).reshape(2, 2)
 
print('First array:')
print(arr1)
 
print('\nSecond array:')
arr2 = np.array([12, 12])
print(arr2)
 
print('\nAdding the two arrays:')
print(np.add(arr1, arr2))

First array:
[[0. 1.]
 [2. 3.]]

Second array:
[12 12]

Adding the two arrays:
[[12. 13.]
 [14. 15.]]


In [ ]:
print('\nSubtracting the two arrays:')
print(np.subtract(arr1, arr2))
 


Subtracting the two arrays:
[[-12. -11.]
 [-10.  -9.]]


In [ ]:
print('\nMultiplying the two arrays:')
print(np.multiply(arr1, arr2))


Multiplying the two arrays:
[[ 0. 12.]
 [24. 36.]]


In [ ]:
print('\nDividing the two arrays:')
print(np.divide(arr1, arr2))


Dividing the two arrays:
[[0.         0.08333333]
 [0.16666667 0.25      ]]


**numpy.reciprocal()** This function returns the reciprocal of argument, element-wise.

In [ ]:
arr = np.array([25, 1.33, 1, 1, 100])
 
print('Our array is:')
print(arr)
 
print('\nAfter applying reciprocal function:')
print(np.reciprocal(arr))
 
arr2 = np.array([25], dtype = int)
print('\nThe second array is:')
print(arr2)
 
print('\nAfter applying reciprocal function:')
print(np.reciprocal(arr2))

Our array is:
[ 25.     1.33   1.     1.   100.  ]

After applying reciprocal function:
[0.04      0.7518797 1.        1.        0.01     ]

The second array is:
[25]

After applying reciprocal function:
[0]


**numpy.power()**.
This function treats elements in the first input array as base and returns it raised to the power of the corresponding element in the second input array.

In [ ]:
a = np.array([10,100,1000]) 

print ('Our array is:\n' ,a)


print ('\nApplying power function:' )

print (np.power(a,2)) 

print ('\nSecond array:') 

b = (np.array([1,2,3]) )
print(b) 


print ('\nApplying power function again:' )
print (np.power(a,b))

Our array is:
 [  10  100 1000]

Applying power function:
[    100   10000 1000000]

Second array:
[1 2 3]

Applying power function again:
[        10      10000 1000000000]


**numpy.mod()**  .
This function returns the remainder of division of the corresponding elements in the input array. The function numpy.remainder() also produces the same result.

In [ ]:
a = np.array([10,20,30]) 
b = np.array([3,5,7]) 
print ('Applying mod() function:') 
print (np.mod(a,b)) 

print ('\nApplying remainder() function:' )
print (np.remainder(a,b) )

Applying mod() function:
[1 0 2]

Applying remainder() function:
[1 0 2]


**numpy.real()** − returns the real part of the complex data type argument



In [ ]:
a = np.array([-5.6j, 0.2j, 11. , 1+1j]) 
print ('Applying real() function:\n' )
print (np.real(a)) 

Applying real() function:

[-0.  0. 11.  1.]


**numpy.imag()** − returns the imaginary part of the complex data type argument.

In [ ]:
a = np.array([-5.6j, 0.2j, 11. , 1+1j]) 
print ('Applying imag() function:' )
print (np.imag(a)) 


Applying imag() function:
[-5.6  0.2  0.   1. ]


**numpy.conj()**− returns the complex conjugate, which is obtained by changing the sign of the imaginary part.

In [ ]:
a = np.array([-5.6j, 0.2j, 11. , 1+1j]) 
print ('Applying conj() function:' )
print (np.conj(a) )


Applying conj() function:
[-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]


**numpy.angle()** − returns the angle of the complex argument. The function has degree parameter. If true, the angle in the degree is returned, otherwise the angle is in radians.

In [ ]:
a = np.array([-5.6j, 0.2j, 11. , 1+1j]) 
print ('Applying angle() function:') 
print (np.angle(a) )


Applying angle() function:
[-1.57079633  1.57079633  0.          0.78539816]


In [ ]:
print ('Applying angle() function again (result in degrees)') 
print (np.angle(a, deg = True))

Applying angle() function again (result in degrees)
[-90.  90.   0.  45.]


LINEAR ALGEBRA ON MATRICES

Dot and matrix product of two arrays

In [ ]:
a=np.array([1,2,3])
b=np.array([2,3,4])
#matrix elements multiplication
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
print("dot product of one dimension is :\n",np.dot(a,b))
#matrix multiplication
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])
c=np.multiply(a,b)
print("element multiplication of matrix:\n",c)


dot product of one dimension is :
 [[ 7 10]
 [15 22]]
element multiplication of matrix:
 [[ 1  4]
 [ 9 16]]


Compute the Eigen values of a matrix

In [ ]:
a=np.array([[1,2],[3,4]])
eigvalues,eigvectors=np.linalg.eig(a)
print("eigen value:\n",eigvalues,"\neigen vector:\n",eigvectors)

eigen value:
 [-0.37228132  5.37228132] 
eigen vector:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


**linear matric** eqn Solve a linear matrix equation such as 3 * x0 + x1 = 9, x0 + 2 * x1 = 8



In [ ]:
a=np.array([[3,1],[1,2]])
b=np.array([[9],[8]])
a_inv=np.linalg.inv(a)
e=np.matmul(a_inv,b)
print("linear equation:\n",e)
print("Identity matrix:\n",np.matmul(a_inv,a))

linear equation:
 [[2.]
 [3.]]
Identity matrix:
 [[1. 0.]
 [0. 1.]]


Compute the multiplicative inverse,rank,Determinant of a matrix

In [ ]:
#@title
a=np.array([[3,1],[1,2]])
a_inv=np.linalg.inv(a)
print("'a' inverse:\n",a_inv)
#matric rank
a=np.array([[3,1],[1,2]])
b=np.linalg.matrix_rank(a)
print("rank:\n",b)
#determinant of array
a=np.array([[3,1],[1,2]])
c=np.linalg.det(a)
print("Determinant:\n",c)

'a' inverse:
 [[ 0.4 -0.2]
 [-0.2  0.6]]
rank:
 2
Determinant:
 5.000000000000001
